import javax.xml.parsers.DocumentBuilderFactory
import org.w3c.dom.Element

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

// ------------------------------------------------------------------ tile symbols
//
// The drawings behind `TileSymbol` are SVGs under `core/ui/icons/` — vendored from Lucide, plus
// two drawn here — and this turns them into one Kotlin file of path data.
//
// Generated rather than committed: a committed copy is a second version of every drawing that can
// fall out of step with the first. Generated rather than read at runtime: this never changes
// between builds, and the start screen is the one screen that has to appear immediately.
//
// The path data is **not** parsed here. Compose's own `PathParser` reads the same `d` syntax the
// SVG already uses, so a drawing crosses into Kotlin as the string it was. That is why this is
// fifty lines rather than a curve library — the only thing it has to understand is which elements
// exist and whether each is stroked or filled.
val generateTileSymbols = tasks.register("generateTileSymbols") {
    group = "build"
    description = "Turns core/ui/icons/**/*.svg into Kotlin path data for TileSymbol."

    val iconDirs = listOf(
        layout.projectDirectory.dir("icons/lucide").asFile,
        layout.projectDirectory.dir("icons/larova").asFile,
    )
    val outputDir = layout.buildDirectory.dir("generated/tileSymbols/kotlin").get().asFile

    inputs.files(iconDirs.map { dir -> fileTree(dir) { include("*.svg") } })
    outputs.dir(outputDir)

    doLast {
        // Declared in here rather than at the top of the script. A script-level `fun` referenced
        // from `doLast` captures the build script object, which the configuration cache refuses to
        // serialise — the same trap `app/build.gradle.kts` documents for script-level `val`s.
        fun quoted(value: String) = "\"" + value + "\""

        /** A circle as two arcs, which is the only way `d` draws one. */
        fun circlePath(node: Element): String {
            val cx = node.getAttribute("cx").toFloat()
            val cy = node.getAttribute("cy").toFloat()
            val r = node.getAttribute("r").toFloat()
            return "M" + (cx - r) + "," + cy + " a" + r + "," + r + " 0 1,0 " + (r * 2) + ",0" +
                " a" + r + "," + r + " 0 1,0 " + (-r * 2) + ",0"
        }

        fun linePath(node: Element): String =
            "M" + node.getAttribute("x1") + "," + node.getAttribute("y1") +
                " L" + node.getAttribute("x2") + "," + node.getAttribute("y2")

        /** Every rect in the set is rounded; the square branch is for the next one that is not. */
        fun rectPath(node: Element): String {
            val x = node.getAttribute("x").toFloat()
            val y = node.getAttribute("y").toFloat()
            val w = node.getAttribute("width").toFloat()
            val h = node.getAttribute("height").toFloat()
            val r = node.getAttribute("rx").ifEmpty { "0" }.toFloat()
            if (r == 0f) return "M" + x + "," + y + " h" + w + " v" + h + " h" + (-w) + " z"
            return "M" + (x + r) + "," + y + " h" + (w - r * 2) +
                " a" + r + "," + r + " 0 0 1 " + r + "," + r +
                " v" + (h - r * 2) + " a" + r + "," + r + " 0 0 1 " + (-r) + "," + r +
                " h" + (-(w - r * 2)) + " a" + r + "," + r + " 0 0 1 " + (-r) + "," + (-r) +
                " v" + (-(h - r * 2)) + " a" + r + "," + r + " 0 0 1 " + r + "," + (-r) + " z"
        }

        val files = iconDirs
            .flatMap { dir -> dir.listFiles()?.filter { it.extension == "svg" }.orEmpty() }
            .sortedBy { it.nameWithoutExtension }
        require(files.isNotEmpty()) { "No SVGs under core/ui/icons — was the folder moved?" }

        val documents = DocumentBuilderFactory.newInstance().newDocumentBuilder()
        val text = StringBuilder()
        text.append("// Generated by :core:ui:generateTileSymbols from core/ui/icons/**/*.svg.\n")
        text.append("// Do not edit: edit the SVG and rebuild. See core/ui/icons/README.md.\n")
        text.append("package app.larova.core.ui.icon\n\n")
        text.append("internal val SYMBOL_PATHS: Map<String, List<SymbolPath>> = mapOf(\n")

        for (file in files) {
            val root = documents.parse(file).documentElement
            val shapes = mutableListOf<String>()
            val children = root.childNodes
            for (i in 0 until children.length) {
                val node = children.item(i) as? Element ?: continue
                val data = when (node.tagName) {
                    "path" -> node.getAttribute("d")
                    "circle" -> circlePath(node)
                    "line" -> linePath(node)
                    "rect" -> rectPath(node)
                    // Loud rather than silent: an icon quietly missing a stroke is the kind of
                    // thing nobody notices until it is on somebody's home screen.
                    else -> error("${file.name}: <${node.tagName}> is not handled here")
                }
                val filled = node.getAttribute("fill") == "currentColor"
                shapes += "        SymbolPath(" + quoted(data) + (if (filled) ", filled = true" else "") + "),"
            }
            require(shapes.isNotEmpty()) { "${file.name} has nothing to draw" }
            text.append("    " + quoted(file.nameWithoutExtension) + " to listOf(\n")
            shapes.forEach { text.append(it).append("\n") }
            text.append("    ),\n")
        }

        text.append(")\n")

        val out = File(outputDir, "app/larova/core/ui/icon/SymbolPaths.kt")
        out.parentFile.mkdirs()
        out.writeText(text.toString())
        logger.lifecycle("Generated ${files.size} tile symbols.")
    }
}

kotlin {
    android {
        // Without this, no string in the app has any text.
        //
        // `com.android.kotlin.multiplatform.library` ships with Android resources switched off, so
        // the variant has no assets for anything to be added to. The Compose plugin puts the
        // compiled strings there — and does it through `variant.sources.assets?.…`, so with assets
        // absent it silently does nothing: the files are generated under build/, the accessors
        // compile, the build passes, and `stringResource` throws on the first screen because the
        // APK contains no `composeResources/` at all.
        //
        // Nothing catches this but running the app or opening the APK. Check
        // `assets/composeResources/**/strings.commonMain.cvr` is in there before trusting a build.
        androidResources.enable = true
        namespace = "app.larova.core.ui"
        compileSdk = providers.gradleProperty("larova.compileSdk").get().toInt()
        minSdk = providers.gradleProperty("larova.minSdk").get().toInt()
        withHostTestBuilder {}
    }

    sourceSets {
        commonMain {
            // The generated path data compiles as part of this module rather than being committed
            // beside the SVGs it came from.
            kotlin.srcDir(generateTileSymbols)
        }
        commonMain.dependencies {
            api(project(":core:domain"))
            api(compose.runtime)
            api(compose.foundation)
            api(compose.material3)
            api(compose.ui)
            // Strings live here, not in :app — the screens are in commonMain of this module and
            // of :feature:*, which cannot see an Android R class. Same XML, same rules.
            api(compose.components.resources)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

compose.resources {
    publicResClass = true
    packageOfResClass = "app.larova.core.ui.resources"
    generateResClass = auto
}
